###
GET https://m4-backend-nextjs.fgp.one/products

###
POST https://m4-backend-nextjs.fgp.one/users/register
Content-Type: application/json
token: autenticado

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "securepassword",
 "address": "123 Main St",
  "phone": "555-1234"
}

###
POST https://m4-backend-nextjs.fgp.one/users/login
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "securepassword"
}

###
POST https://m4-backend-nextjs.fgp.one/orders/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczMDEyNjQ0OX0.R1MHUWGG37DBIdHehD-TwoJkEcge79_3FuI5vGJARBk

{
   "userId" : 1,
  "products": [1, 2, 3]
}

###
GET https://m4-backend-nextjs.fgp.one/users/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczMDEyNjQ0OX0.R1MHUWGG37DBIdHehD-TwoJkEcge79_3FuI5vGJARBk
